"""add group to tenant_tools

Revision ID: cca41842b1df
Revises: 5fb9d9770ab5
Create Date: 2026-04-07 19:34:15.646144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cca41842b1df'
down_revision: Union[str, None] = '5fb9d9770ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_tools', sa.Column('group', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_tenant_tools_group'), 'tenant_tools', ['group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_tools_group'), table_name='tenant_tools')
    op.drop_column('tenant_tools', 'group')
    # ### end Alembic commands ###
